#!/bin/bash

# You can call this script like this:
# $./volume.sh up
# $./volume.sh down
# $./volume.sh mute
VAR=$2
function get_volume {
    amixer -c 0 get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1
}

function is_mute {
    amixer -c 0 get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

function send_notification {
    volume=`get_volume`
    # Make the bar with the special character ─ (it's not dash -)
    # https://en.wikipedia.org/wiki/Box-drawing_character
    bar=$(seq -s "─" $(($volume / 5)) | sed 's/[0-9]//g')
    # Send the notification
    dunstify -i high_vol -t 1000 -r 2598 -u normal " $volume    $bar"
}
case $1 in
    up)
	## Set the volume on (if it was muted)
	amixer -c 0 set Master on > /dev/null
	## Up the volume (+ 5%)
	amixer -c 0 sset Master 2%+ > /dev/null
	send_notification
	;;
    down)
	amixer -c 0 set Master on > /dev/null
	amixer -c 0 sset Master 2%- > /dev/null
	send_notification
	;;
   mute)
    amixer -c 0 set Master 1+ toggle 
        dunstify -i notification-audio-volume-muted -t 1000 -r 2599 -u normal "Mute"
  ;;
esac
